### ISSUE TITLE
502 on efa-api.asw.io

### ISSUE THREAD

**Issue by dynobo** [opendata-stuttgart/metaEFA#10]
metaEFA is running fine on my local machine, but I get an 502 on the hosted version https://efa-api.asw.io 
Any chance to fix this? :-)

**Comment by asmaps** [comment]
I can't see any problems.

**Comment by dynobo** [comment]
It's working again since yesterday. Thought you fixed it... ;) Thanks anyway!

Arne Schauf <notifications@github.com> schrieb am 11.07.2017:
>I can't see any problems.

**Comment by asmaps** [comment]
okay. No I didn't do anything. In the most cases 502 means, that the VVS API does not respond, so I can't really do anything about that :-(

**Comment by mfa** [comment]
same problem on kiosk in shackspace. No data metaefa/vvs -> no departure times for U4/U9. :(

**Comment by dynobo** [comment]
Does Vvs-API has limits, that might be reached? Maybe metaEFA became too popular... :)

Andreas Madsack <notifications@github.com> schrieb am 12.07.2017:
>same problem on kiosk in shackspace. No data metaefa/vvs -> no
>departure times for U4/U9. :(
