### ISSUE TITLE
API Server down?

### ISSUE THREAD

**Issue by kajetanschuler** [opendata-stuttgart/metaEFA#14]
Hi,

since yesterday, i can't make any API calls. Either I get SSL Handshake Errors with Android or Request failed with browsers. Even the demo site is not working?

Is there any information?

Thanks!

**Comment by VincentKoehler** [comment]
Hi. It looks like the SSL certificate expired and has to be renewed manually.

**Comment by kajetanschuler** [comment]
Hi. Thanks for the reply. Are you planning to renew the SSL certificate?

Best regards

Am 04.10.2017 10:55 schrieb "VincentKoehler" <notifications@github.com>:

**Comment by VincentKoehler** [comment]
I'm not a member of the metaEFA team. Last time asmaps renewed it:
https://github.com/opendata-stuttgart/metaEFA/issues/12

**Comment by kajetanschuler** [comment]
Seems to work again!
