### ISSUE TITLE
In Hosted Version the API ist editable by everyone

### ISSUE THREAD

**Issue by KornPhleax** [opendata-stuttgart/metaEFA#17]
I notized this while checking out the [Hosted Version](https://efa-api.asw.io/api/v1/)
Is this the desired behaviour? Somebody could delete every entry, or put in new ones. 
Maybe it would be a better idea to restrict the access on the hosted api. 
I get that in order to use this api, i schould host it myself, and this is just a demo, nevertheless someone 
could potentially f*ck with it :D

**Comment by KornPhleax** [comment]
ok, but what did i just edit then? i don't really know if this is even relevant, just curios.
[Take a look at this](https://efa-api.asw.io/api/v1/station/5033400/)

**Comment by mfa** [comment]
ok, you should not be able to edit the station entries. this is a bug.

@asmaps ^

**Comment by asmaps** [comment]
Thanks for the hint
