### ISSUE TITLE
api seems to be broken

### ISSUE THREAD

**Issue by MaCXyLo** [opendata-stuttgart/metaEFA#20]
can't search for stations anymore:
http://efa.asw.io/

**Comment by aschuma** [comment]
<pre>curl -v https://efa-api.asw.io/api/v1/station/5006074/departures/ --verbose
*   Trying 94.23.161.177...
* TCP_NODELAY set
* Connection failed
* connect to 94.23.161.177 port 443 failed: Operation timed out
* Failed to connect to efa-api.asw.io port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to efa-api.asw.io port 443: Operation timed out</pre>

**Comment by asmaps** [comment]
Hmm... I shut down the VM, as I thought there's nothing important on it... Turned it back on.
