### ISSUE TITLE
metaEFA as codefor.de/OK Lab Stuttgart project

### ISSUE THREAD

**Issue by michael-k** [opendata-stuttgart/metaEFA#4]
@fuergestalten would love to see `metaEFA` listed as an *OK¹ Lab Stuttgart* project.  Anyone opposed to this idea?

*Background*: The OK Lab Stuttgart has only one project ([dust sensors](http://codefor.de/projekte/2015-04-28-stgt-dust-sensor.html)) at the moment and is at risk of getting reduced to that.

¹Open Knowledge

**Comment by asmaps** [comment]
+1 :-)
Maybe we can also move the project to the opendata-stuttgart org

**Comment by momorientes** [comment]
fine with me

**Comment by asmaps** [comment]
@momorientes is it possible to move the repo or do we have to create a fork?

**Comment by momorientes** [comment]
if someone can give me admin rights to opendata-stuttgart I can make the transfer

**Comment by asmaps** [comment]
done

**Comment by momorientes** [comment]
done
