### ISSUE TITLE
How to make a trip request?

### ISSUE THREAD

**Issue by sebastianwachter** [opendata-stuttgart/metaEFA#6]
How do you make a trip request?<br/>Let's say I want to know when my Train from Stadtmitte to Böblingen leaves. How can I achieve this with this API?<br/>I already know how to find stations and how to get the departures from that station. But I don't know how I can connect these.

**Comment by mfa** [comment]
this is not implemented (yet).

feel free to add it. :)

**Comment by sebastianwachter** [comment]
is there a way where i can read the documentation of the original api?

**Comment by asmaps** [comment]
maybe a little bit late for an answer, but better late than never :-D
The best freely accessible docs about EFA I found until now is this presentation: http://data.linz.gv.at/katalog/linz_ag/linz_ag_linien/fahrplan/LINZ_AG_Linien_Schnitstelle_EFA_v7_Echtzeit.pdf
