### ISSUE TITLE
Stuttgart (VVS) only?

### ISSUE THREAD

**Issue by gehwissenlos** [opendata-stuttgart/metaEFA#7]
Is this only for the Stuttgarter region? A station in Ravensburg for example doesn't work:
https://efa-api.asw.io/api/v1/station/7708079/?format=json
But on EFA it is found:
https://www.ding.eu/departure/XSLT_DM_REQUEST?name_dm=7708079&type_dm=any&locationServerActive=1&stateless=1&itdLPxx_fontSize=30px&itdLPxx_colorBgHead=FCC300&itdLPxx_text=Abfahrten%20der%20Busse%20und%20Bahnen&itdLPxx_footer=Gute%20Fahrt

**Comment by mfa** [comment]
it is stuttgart only until someone adds stations for other regions.
